---
sudo: required
language: python
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
script:
  - molecule lint -s monitoring
notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/?branch=master
    on_failure: never
