---
- name: "Create dirs"
  file:
    path: "{{ dir }}"
    state: directory
  with_items:
    - "{{ bc_path_general }}/bench"
    - "{{ bc_path_general }}/bench/config"
  loop_control:
    loop_var: dir

- name: "Create common config"
  template:
    src: "configs/bench/bench.config.json.j2"
    dest: "{{ bc_path_general }}/bench/config/bench.config.json"

- name: "Create config for polkadot"
  template:
    src: "configs/bench/polkadot.bench.config.json.j2"
    dest: "{{ bc_path_general }}/bench/config/polkadot.bench.config.json"
