---
- name: "Create dirs"
  file:
    path: "{{ dir }}"
    state: directory
  with_items:
    - "{{ bc_path_general }}/bench"
    - "{{ bc_path_general }}/bench/config"
  loop_control:
    loop_var: dir

- name: "Create common config"
  template:
    src: "configs/bench/bench.config.json.j2"
    dest: "{{ bc_path_general }}/bench/config/bench.config.json"

- name: "Create config for polkadot"
  template:
    src: "configs/bench/polkadot.bench.config.json.j2"
    dest: "{{ bc_path_general }}/bench/config/polkadot.bench.config.json"

- name: "Start bench container"
  docker_container:
    name: "bench"
    image: "scaptaincap/tank.bench-common:latest"
    command: |
      npm run start -- {{ load_profile_file_in_container }}
    volumes:
      - "{{ bc_path_general }}/bench/config/bench.config.json:/bench.config.json"
      - "{{ bc_path_general }}/bench/config/polkadot.bench.config.json:/module.config.json"
      - "{{ load_profile_remote_file }}:{{ load_profile_file_in_container }}"
    stop_timeout: 600
    detach: no
    pull: true
