---
- name: Add producers to group producers
  tags:
    - always
  add_host:
    name: "{{ item }}"
    groups: producers
    inventory_dir: "{{ hostvars[item].inventory_dir }}"
  loop: "{{ groups['all'] }}"
  when: '"prod" in hostvars[item]["ansible_hostname"]'
  changed_when: false

- name: Converge boot node
  hosts: "*boot*"
  become: true
  gather_facts: smart
  vars:
    bc_polkadot_comp_state_boot: present
    bc_producers_count: "{{ group['producers'] | length }}"
    install_promstack: true
  roles:
    - role: tank.blockchain
  tasks:
    - debug: msg="Bootstrap instance ready"
      tags: [print_action]

- name: Converge validator node
  hosts: "*prod*"
  become: true
  gather_facts: smart
  vars:
    bc_polkadot_comp_state_prod: present
    bc_polkadot_comp_state_bench: present
    install_promstack: true
    bc_polkadot_extra_validator_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shard_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_polkadot_bench_shards: "{{ play_hosts | length }}"
    bc_producers_count: "{{ group['producers'] | length }}"
  roles:
    - role: tank.blockchain
  tasks:
    - name: "Show bc_polkadot_extra_validator_id"
      tags:
        - update
      debug:
        msg: "{{ bc_polkadot_extra_validator_id }}"
    - debug: msg="Validator instance(s) ready"
      tags: [print_action]
    - set_fact:
        bench_present: true
