---

- name: "Make directory structure"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_config }}"
    - "{{ bc_path_state }}"


- name: Start boot-node container
  register: _start_boot_node
  docker_container:
    name: "{{ bc_name }}-{{ bc_component_name }}"
    image: "{{ bc_polkadot_image }}"
    command: |
      /usr/local/bin/polkadot -d /state
      --chain=bench --validator --key //Alice --ws-external --rpc-external
      --node-key-type ed25519 --node-key 1111111111111111111111111111111111111111111111111111111111111111
    hostname: "{{ bc_name }}-{{ bc_component_name }}"
    network_mode: host
    volumes:
      - "{{ bc_path_state }}:/state"
      - "/tmp/cores:/tmp/cores"
    stop_timeout: 600
    pull: true
    env:
      EXTRA_VALIDATORS: "{{ bc_peers_ip|length - 1 }}"


- name: Start boot-node metric exporter container
  docker_container:
    name: "{{ bc_name }}-{{ bc_component_name }}-metrics"
    image: "{{ bc_polkadot_exporter_image }}"
    command: --exporter_port "{{ bc_polkadot_node_metrics_port }}"
    hostname: "{{ bc_name }}-{{ bc_component_name }}-metrics"
    network_mode: host
    stop_timeout: 600
    pull: true


- name: "Waiting"
  pause:
    seconds: 15
  when:
    - _start_boot_node is changed
