---

- name: "Make directory structure"
  tags:
    - prod
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_config }}"
    - "{{ bc_path_state }}"


- name: "Start {{ bc_name }}-{{ bc_component_name }} container"
  register: "{{ bc_name }}_{{ bc_component_name }}"
  docker_container:
    name: "{{ bc_name }}-{{ bc_component_name }}"
    image: "{{ bc_polkadot_image }}"
    command: |
      /usr/local/bin/polkadot -d /state
      --chain=bench --validator --key "//v{{ bc_polkadot_extra_validator_id }}" --ws-external
      --bootnodes "/ip4/{{ bc_boot_ip[0] }}/tcp/30333/p2p/QmXS53cQyDRT7RaXiKYLjfkX8xSc9pBDPohDh1F3HxzjAz"
    hostname: "{{ bc_name }}-{{ bc_component_name }}"
    network_mode: host
    volumes:
      - "{{ bc_path_state }}:/state"
      - "/tmp/cores:/tmp/cores"
    stop_timeout: 600
    pull: true
    env:
      EXTRA_VALIDATORS: "{{ bc_peers_ip|length - 1 }}"


- name: List data about prod container
  debug:
    var="{{ bc_name }}_{{ bc_component_name }}"
  tags:
    - never
    - debug
